# Auto-generated DLL fix script v2
# Generated by dll_analyzer.py

$DestDir = 'C:\Zhiyaun\r\Slicer-build\bin\Release'
New-Item -ItemType Directory -Path $DestDir -Force | Out-Null

$fixes = @(
    @('C:\Zhiyaun\r\LibArchive-build\bin\Release\archive.dll', 'archive.dll'),
    @('C:\Zhiyaun\r\CTK-build\CTK-build\bin\Release\ctkcore.dll', 'ctkcore.dll'),
    @('C:\Zhiyaun\r\CTK-build\CTK-build\bin\Release\ctkdicomcore.dll', 'ctkdicomcore.dll'),
    @('C:\Zhiyaun\r\CTK-build\CTK-build\bin\Release\ctkdicomwidgets.dll', 'ctkdicomwidgets.dll'),
    @('C:\Zhiyaun\r\CTK-build\CTK-build\bin\Release\ctkimageprocessingitkcore.dll', 'ctkimageprocessingitkcore.dll'),
    @('C:\Zhiyaun\r\CTK-build\CTK-build\bin\Release\ctkscriptingpythoncore.dll', 'ctkscriptingpythoncore.dll'),
    @('C:\Zhiyaun\r\CTK-build\CTK-build\bin\Release\ctkscriptingpythonwidgets.dll', 'ctkscriptingpythonwidgets.dll'),
    @('C:\Zhiyaun\r\CTK-build\CTK-build\bin\Release\ctkvisualizationvtkcore.dll', 'ctkvisualizationvtkcore.dll'),
    @('C:\Zhiyaun\r\CTK-build\CTK-build\bin\Release\ctkvisualizationvtkwidgets.dll', 'ctkvisualizationvtkwidgets.dll'),
    @('C:\Zhiyaun\r\CTK-build\CTK-build\bin\Release\ctkwidgets.dll', 'ctkwidgets.dll'),
    @('C:\Zhiyaun\r\DCMTK-build\bin\Release\dcmdata.dll', 'dcmdata.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkcommon-5.4.dll', 'itkcommon-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkgrowcut-5.4.dll', 'itkgrowcut-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiobiorad-5.4.dll', 'itkiobiorad-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiobmp-5.4.dll', 'itkiobmp-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiodcmtk-5.4.dll', 'itkiodcmtk-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiogdcm-5.4.dll', 'itkiogdcm-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiogipl-5.4.dll', 'itkiogipl-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkioimagebase-5.4.dll', 'itkioimagebase-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiojpeg-5.4.dll', 'itkiojpeg-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiolsm-5.4.dll', 'itkiolsm-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiometa-5.4.dll', 'itkiometa-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiominc-5.4.dll', 'itkiominc-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiomrc-5.4.dll', 'itkiomrc-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkionifti-5.4.dll', 'itkionifti-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkionrrd-5.4.dll', 'itkionrrd-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiopng-5.4.dll', 'itkiopng-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkioscanco-5.4.dll', 'itkioscanco-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiostimulate-5.4.dll', 'itkiostimulate-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiotiff-5.4.dll', 'itkiotiff-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiotransformbase-5.4.dll', 'itkiotransformbase-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiotransformhdf5-5.4.dll', 'itkiotransformhdf5-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiotransforminsightlegacy-5.4.dll', 'itkiotransforminsightlegacy-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiotransformmatlab-5.4.dll', 'itkiotransformmatlab-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkiovtk-5.4.dll', 'itkiovtk-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itklabelmap-5.4.dll', 'itklabelmap-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkmghio-5.4.dll', 'itkmghio-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkspatialobjects-5.4.dll', 'itkspatialobjects-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkstatistics-5.4.dll', 'itkstatistics-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itktransform-5.4.dll', 'itktransform-5.4.dll'),
    @('C:\Zhiyaun\r\ITK-build\bin\Release\itkvtk-5.4.dll', 'itkvtk-5.4.dll'),
    @('C:\Zhiyaun\r\ex-OpenSSL1234\OpenSSL_1_1_1g-install-msvc1900-64\Release\bin\libcrypto-1_1-x64.dll', 'libcrypto-1_1-x64.dll'),
    @('C:\Zhiyaun\r\ex-OpenSSL1234\OpenSSL_1_1_1g-install-msvc1900-64\Release\bin\libssl-1_1-x64.dll', 'libssl-1_1-x64.dll'),
    @('C:\Zhiyaun\r\SlicerExecutionModel-build\ModuleDescriptionParser\bin\Release\moduledescriptionparser.dll', 'moduledescriptionparser.dll'),
    @('C:\LHT_workspace\code\Qt5.15\5.15.2\msvc2019_64\bin\Qt5Core.dll', 'qt5core.dll'),
    @('C:\LHT_workspace\code\Qt5.15\5.15.2\msvc2019_64\bin\Qt5Gui.dll', 'qt5gui.dll'),
    @('C:\LHT_workspace\code\Qt5.15\5.15.2\msvc2019_64\bin\Qt5Network.dll', 'qt5network.dll'),
    @('C:\LHT_workspace\code\Qt5.15\5.15.2\msvc2019_64\bin\Qt5Qml.dll', 'qt5qml.dll'),
    @('C:\LHT_workspace\code\Qt5.15\5.15.2\msvc2019_64\bin\Qt5Test.dll', 'qt5test.dll'),
    @('C:\LHT_workspace\code\Qt5.15\5.15.2\msvc2019_64\bin\Qt5WebChannel.dll', 'qt5webchannel.dll'),
    @('C:\LHT_workspace\code\Qt5.15\5.15.2\msvc2019_64\bin\Qt5WebEngineWidgets.dll', 'qt5webenginewidgets.dll'),
    @('C:\LHT_workspace\code\Qt5.15\5.15.2\msvc2019_64\bin\Qt5Widgets.dll', 'qt5widgets.dll'),
    @('C:\LHT_workspace\code\Qt5.15\5.15.2\msvc2019_64\bin\Qt5Xml.dll', 'qt5xml.dll'),
    @('C:\Zhiyaun\r\ex-tbb1234\oneapi-tbb-2021.5.0\redist\intel64\vc14\tbb12.dll', 'tbb12.dll'),
    @('C:\Zhiyaun\r\teem-build\bin\Release\teem.dll', 'teem.dll'),
    @('C:\Windows\System32\ucrtbased.dll', 'ucrtbased.dll'),
    @('C:\Windows\System32\vcruntime140d.dll', 'vcruntime140d.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkchartscore-9.4.dll', 'vtkchartscore-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkcommon-9.4.dll', 'vtkcommon-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkfilters-9.4.dll', 'vtkfilters-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkfiltershybrid-9.4.dll', 'vtkfiltershybrid-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkguisupportqt-9.4.dll', 'vtkguisupportqt-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkimaging-9.4.dll', 'vtkimaging-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkinteraction-9.4.dll', 'vtkinteraction-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkio-9.4.dll', 'vtkio-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkioexport-9.4.dll', 'vtkioexport-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkioexportgl2ps-9.4.dll', 'vtkioexportgl2ps-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkioinfovis-9.4.dll', 'vtkioinfovis-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkopengl-9.4.dll', 'vtkopengl-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkparallel-9.4.dll', 'vtkparallel-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkrendering-9.4.dll', 'vtkrendering-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtksys-9.4.dll', 'vtksys-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtktestingrendering-9.4.dll', 'vtktestingrendering-9.4.dll'),
    @('C:\Zhiyaun\r\VTK-build\bin\Release\vtkwrappingpythoncore3.12-9.4.dll', 'vtkwrappingpythoncore3.12-9.4.dll'),
    @('C:\Windows\System32\wsock32.dll', 'wsock32.dll'),
    @('C:\Zhiyaun\r\JsonCpp-build\bin\Release\jsoncpp.dll', 'jsoncpp.dll'),
    @('C:\Zhiyaun\r\CTK-build\CMakeExternals\Install\bin\PythonQt.dll', 'pythonqt.dll')
)

$successCount = 0
$failCount = 0

foreach ($fix in $fixes) {
    $src = $fix[0]
    $dest = Join-Path $DestDir $fix[1]
    if (Test-Path $src) {
        try {
            Copy-Item -Path $src -Destination $dest -Force
            Write-Host "  [OK] Copied $($fix[1])" -ForegroundColor Green
            $successCount++
        } catch {
            Write-Host "  [FAIL] $($fix[1]): $_" -ForegroundColor Red
            $failCount++
        }
    } else {
        Write-Host "  [MISSING] Source not found: $src" -ForegroundColor Yellow
        $failCount++
    }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "DLL Fix Complete: $successCount copied, $failCount failed" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
